security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: bcrypt
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/auth/login
            stateless: true
            json_login:
                check_path:              /api/auth/login
                username_path:           email
                password_path:           password
                success_handler:         lexik_jwt_authentication.handler.authentication_success
                failure_handler:         lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

    access_control:
        # Public
        - { path: ^/api/auth/login,       roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register,    roles: PUBLIC_ACCESS }
        - { path: ^/api/menus,            roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/horaires,         roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/contact,          roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/auth/forgot-password,  roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/reset-password,   roles: PUBLIC_ACCESS }
        - { path: ^/api/commandes/livraison, roles: PUBLIC_ACCESS, methods: [GET] }

        # Utilisateur connecté
        - { path: ^/api/commandes,        roles: ROLE_USER }
        - { path: ^/api/utilisateur,      roles: ROLE_USER }
        - { path: ^/api/avis,             roles: ROLE_USER, methods: [POST] }
        

        # Employé
        - { path: ^/api/employe,          roles: ROLE_EMPLOYE }
        - { path: ^/api/plats, roles: ROLE_EMPLOYE }
        - { path: ^/api/upload, roles: ROLE_EMPLOYE }

        # Admin uniquement
        - { path: ^/api/admin,            roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_EMPLOYE: ROLE_USER
        ROLE_ADMIN:   ROLE_EMPLOYE
