# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\MongoService:
        arguments:
            $mongoUri: '%env(MONGO_URI)%'
            $mongoDB:  '%env(MONGO_DB)%'

    App\Service\DeliveryService:
        arguments:
            $orsApiKey: '%env(ORS_API_KEY)%'

    App\Controller\UploadController:
        arguments:
            $uploadDir: '%kernel.project_dir%/public/images'
